-- Create Database--
CREATE DATABASE QUAN_LY_CAR_SHOP
ON PRIMARY
	(
	NAME = QLCarShop, 
	FILENAME = 'F:\CARSHOP.MDF', 
	SIZE = 2, 
	MAXSIZE = 10, 
	FILEGROWTH = 1
	)
LOG ON
	(
	NAME = LOGFILE, 
	FILENAME = 'F:\CARSHOP_LOG.LDF', 
	SIZE = 2, 
	MAXSIZE = 10, 
	FILEGROWTH = 1
	)
GO

USE QUAN_LY_CAR_SHOP

GO

/* CREATE TABLE */

CREATE TABLE MAU
(
	MA CHAR(10) PRIMARY KEY,
	MAU NVARCHAR(15) UNIQUE NOT NULL,
)

CREATE TABLE LOAI_XE
(
	MA INT PRIMARY KEY IDENTITY(1, 1),
	TEN_LOAI_XE NVARCHAR(30) UNIQUE NOT NULL,
	GHI_CHU NVARCHAR(200)
)

CREATE TABLE KIEU_XE
(
	MA INT PRIMARY KEY IDENTITY(1, 1),
	MA_LOAI_XE INT NOT NULL,
	TEN_KIEU_XE NVARCHAR(30) UNIQUE NOT NULL,
)

ALTER TABLE KIEU_XE
ADD
	CONSTRAINT FK_LOAIXE_KIEUXE FOREIGN KEY (MA_LOAI_XE) REFERENCES LOAI_XE

CREATE TABLE HANG_SAN_XUAT
(
	MA INT PRIMARY KEY IDENTITY(1, 1),
	TEN_HANG_XE NVARCHAR(256) UNIQUE NOT NULL,
)


CREATE TABLE XE
(
	MA INT PRIMARY KEY IDENTITY(1, 1),
	TEN_XE NVARCHAR(50) UNIQUE NOT NULL,
	MA_KIEU_XE INT NOT NULL,
	MA_HANG_XE INT NOT NULL,
	DOI_XE INT NOT NULL,
	CHI_SO_NHIEN_LIEU DECIMAL,
	MAX_SPEED INT,
	LOAI_DIA_HINH NVARCHAR(100),
	SO_CHO_NGOI INT DEFAULT 0,
	GIA_TIEN_BAN MONEY NOT NULL,
	GIA_TIEN_MUA MONEY NOT NULL,
	SO_LUONG INT NOT NULL,
)

ALTER TABLE XE
ADD
	CONSTRAINT FK_KIEUXE_XE FOREIGN KEY (MA_KIEU_XE) REFERENCES KIEU_XE,
	CONSTRAINT FK_HANGXE_XE FOREIGN KEY (MA_HANG_XE) REFERENCES HANG_SAN_XUAT

CREATE TABLE MAU_XE
(
	MA_XE INT NOT NULL,
	MA_MAU CHAR(10) NOT NULL,
	SO_LUONG INT NOT NULL,
)

ALTER TABLE MAU_XE
ADD
	CONSTRAINT PK_MAUXE PRIMARY KEY(MA_XE, MA_MAU),
	CONSTRAINT FK_MAU_MAUXE FOREIGN KEY (MA_MAU) REFERENCES MAU,
	CONSTRAINT FK_XE_MAUXE FOREIGN KEY (MA_XE) REFERENCES XE

CREATE TABLE KHACH_HANG
(
	MA INT PRIMARY KEY IDENTITY(1, 1),
	HO_TEN NVARCHAR(40) UNIQUE NOT NULL,
	PHAI BIT NOT NULL, -- NAM: 1, NU: 0--
	DIA_CHI NVARCHAR(150) NOT NULL,
	DIEN_THOAI CHAR(10),
	CMND CHAR(9) NOT NULL,
	LOAI_KHACH_HANG BIT NOT NULL, -- 1: KHACH QUEN, 0: KHACH LA--
)

CREATE TABLE LOAI_NHAN_VIEN
(
	MA INT PRIMARY KEY IDENTITY(1, 1),
	TEN_LOAI_NHAN_VIEN NVARCHAR(50) UNIQUE NOT NULL,
)

CREATE TABLE NHAN_VIEN
(
	MA INT PRIMARY KEY IDENTITY(1, 1),
	HO_TEN NVARCHAR(30) UNIQUE NOT NULL,
	MA_LOAI_NHAN_VIEN INT NOT NULL,
	USERNAME NVARCHAR(256) NOT NULL,
	USER_PASSWORD NVARCHAR(256) NOT NULL,
	PHAI BIT NOT NULL, -- NAM: 1, NU: 0--
	NGAY_SINH SMALLDATETIME NOT NULL,
	DIA_CHI NVARCHAR(150) NOT NULL,
	DIEN_THOAI CHAR(11),
	CMND CHAR(9) NOT NULL,
)

ALTER TABLE NHAN_VIEN
ADD
	CONSTRAINT FK_LOAINHANVIEN_NHANVIEN FOREIGN KEY (MA_LOAI_NHAN_VIEN) REFERENCES LOAI_NHAN_VIEN


CREATE TABLE PHIEU_DAT_XE
(
	MA INT PRIMARY KEY IDENTITY(1, 1),
	MA_KHACH_HANG INT NOT NULL,
	MA_NHAN_VIEN INT NOT NULL,
	NGAY_DAT DATETIME NOT NULL,
	NGAY_HEN_LAY SMALLDATETIME NOT NULL,
	TONG_TIEN MONEY NOT NULL,
	TIEN_TRA_TRUOC MONEY NOT NULL,
)

ALTER TABLE PHIEU_DAT_XE	
ADD
	CONSTRAINT FK_KHACHHANG_PHIEUDATXE FOREIGN KEY (MA_KHACH_HANG) REFERENCES KHACH_HANG,
	CONSTRAINT FK_NHANVIEN_PHIEUDATXE FOREIGN KEY (MA_NHAN_VIEN) REFERENCES NHAN_VIEN

CREATE TABLE CHI_TIET_PHIEU_DAT_XE
(
	MA INT PRIMARY KEY IDENTITY(1, 1),
	MA_PHIEU_DAT INT NOT NULL,
	MA_XE INT NOT NULL,
	MA_MAU CHAR(10) NOT NULL,
	SO_LUONG INT NOT NULL,
	TONG_TIEN MONEY NOT NULL,
)

ALTER TABLE CHI_TIET_PHIEU_DAT_XE
ADD
	CONSTRAINT FK_PHIEUDATXE_CTPHIEUDATXE FOREIGN KEY (MA_PHIEU_DAT) REFERENCES PHIEU_DAT_XE,
	CONSTRAINT FK_XE_CTPHIEUDATXE FOREIGN KEY (MA_XE) REFERENCES XE,
	CONSTRAINT FK_MAU_CTPHIEUDATXE FOREIGN KEY (MA_MAU) REFERENCES MAU

CREATE TABLE DON_DAT_HANG
(
	MA INT PRIMARY KEY IDENTITY(1, 1),
	NGAY_DAT SMALLDATETIME NOT NULL,
	TONG_TIEN MONEY NOT NULL,
	TONG_SO_LUONG INT NOT NULL,
)

CREATE TABLE CT_DON_DAT_HANG
(
	MA_DON_DAT_HANG INT NOT NULL,
	MA_XE INT NOT NULL,
	MA_MAU CHAR(10) NOT NULL,
	SO_LUONG INT NOT NULL,
	TONG_TIEN MONEY NOT NULL,
)

ALTER TABLE CT_DON_DAT_HANG
ADD
	CONSTRAINT PK_CTDONDATHANG PRIMARY KEY (MA_DON_DAT_HANG, MA_XE, MA_MAU),
	CONSTRAINT FK_DDH_CTDDH FOREIGN KEY (MA_DON_DAT_HANG) REFERENCES DON_DAT_HANG,
	CONSTRAINT FK_XE_CTDDH FOREIGN KEY (MA_XE) REFERENCES XE,
	CONSTRAINT FK_MAU_CTDDH FOREIGN KEY (MA_MAU) REFERENCES MAU

CREATE TABLE PHIEU_NHAP_XE
(
	MA INT PRIMARY KEY IDENTITY(1, 1),
	MA_DON_DAT_HANG INT NOT NULL,
	NGAY_NHAP SMALLDATETIME NOT NULL,
	TONG_SO_LUONG INT NOT NULL,
)

ALTER TABLE PHIEU_NHAP_XE
ADD
	CONSTRAINT FK_DDH_PHIEUNHAPXE FOREIGN KEY (MA_DON_DAT_HANG) REFERENCES DON_DAT_HANG

CREATE TABLE CT_PHIEU_NHAP_XE
(
	MA_PHIEU_NHAP_XE INT NOT NULL,
	MA_XE INT NOT NULL,
	MA_MAU CHAR(10) NOT NULL,
	SO_LUONG INT NOT NULL,
)

ALTER TABLE CT_PHIEU_NHAP_XE
ADD
	CONSTRAINT PK_CTPHIEUNHAPXE PRIMARY KEY(MA_PHIEU_NHAP_XE, MA_XE, MA_MAU),
	CONSTRAINT FK_CTPHIEUNHAPXE_PHIEUNHAPXE FOREIGN KEY (MA_PHIEU_NHAP_XE) REFERENCES PHIEU_NHAP_XE,
	CONSTRAINT FK_XE_CTPHIEUNHAPXE FOREIGN KEY (MA_XE) REFERENCES XE,
	CONSTRAINT FK_MAU_CTPHIEUNHAPXE FOREIGN KEY (MA_MAU) REFERENCES MAU

CREATE TABLE PHIEU_XUAT_XE
(
	MA INT PRIMARY KEY IDENTITY(1, 1),
	NGAY_XUAT DATETIME NOT NULL,
	MA_NHAN_VIEN INT NOT NULL,
	TONG_SO_LUONG INT NOT NULL,
)
ALTER TABLE PHIEU_XUAT_XE
ADD
	CONSTRAINT FK_NHANVIEN_PHIEUXUATXE FOREIGN KEY (MA_NHAN_VIEN) REFERENCES NHAN_VIEN


CREATE TABLE CHI_TIET_PHIEU_XUAT_XE
(
	MA_PHIEU_XUAT_XE INT NOT NULL,
	MA_XE INT NOT NULL,
	MA_MAU CHAR(10) NOT NULL,
	SO_LUONG INT NOT NULL,
)
ALTER TABLE CHI_TIET_PHIEU_XUAT_XE
ADD
	CONSTRAINT PK_CTPHIEUXUATXE PRIMARY KEY(MA_PHIEU_XUAT_XE,MA_XE,MA_MAU),
	CONSTRAINT FK_PHIEUXUATXE_CTPHIEUXUATXE FOREIGN KEY (MA_PHIEU_XUAT_XE) REFERENCES PHIEU_XUAT_XE,
	CONSTRAINT FK_XE_CTPHIEUXUATXE FOREIGN KEY (MA_XE) REFERENCES XE,
	CONSTRAINT FK_MAU_CTPHIEUXUATXE FOREIGN KEY (MA_MAU) REFERENCES MAU

CREATE TABLE HOA_DON
(
	MA INT PRIMARY KEY IDENTITY(1, 1),
	MA_KHACH_HANG INT NOT NULL,
	MA_NHAN_VIEN INT NOT NULL,
	NGAY_LAP DATETIME NOT NULL,
	KIEU_THANH_TOAN BIT NOT NULL, -- 1: TRA 1 LAN, 0: TRA NHIEU LAN--
	TONG_TIEN MONEY NOT NULL,
	TIEN_TRA_MOI_DOT MONEY NOT NULL DEFAULT 0,
	SO_LAN_TRA INT NOT NULL,
)
	
ALTER TABLE HOA_DON
ADD
	CONSTRAINT FK_KHACHHANG_HOADON FOREIGN KEY (MA_KHACH_HANG) REFERENCES KHACH_HANG,
	CONSTRAINT FK_NHANVIEN_HOADON FOREIGN KEY (MA_NHAN_VIEN) REFERENCES NHAN_VIEN

CREATE TABLE CHI_TIET_HOA_DON
(
	MA INT PRIMARY KEY IDENTITY(1, 1),
	MA_HOA_DON INT NOT NULL,
	MA_XE INT NOT NULL,
	MA_MAU CHAR(10) NOT NULL,
	SO_LUONG INT NOT NULL,
	THANH_TIEN MONEY NOT NULL
)

ALTER TABLE CHI_TIET_HOA_DON
ADD
	CONSTRAINT FK_HOADON_CTHOADON FOREIGN KEY (MA_HOA_DON) REFERENCES HOA_DON,
	CONSTRAINT FK_MAU_CTHOADON FOREIGN KEY (MA_MAU) REFERENCES MAU,
	CONSTRAINT FK_XE_CT_HOADON FOREIGN KEY (MA_XE) REFERENCES XE

CREATE TABLE BIEN_NHAN
(
	MA INT PRIMARY KEY IDENTITY(1, 1),
	MA_HOA_DON INT NOT NULL,
	NGAY_THANH_TOAN DATETIME NOT NULL,
	MA_NHAN_VIEN INT NOT NULL,
	SO_TIEN MONEY NOT NULL,
)

ALTER TABLE BIEN_NHAN
ADD	
	CONSTRAINT FK_HOADON_BIENNHAN FOREIGN KEY (MA_HOA_DON) REFERENCES HOA_DON,
	CONSTRAINT FK_NHANVIEN_BIENNHAN FOREIGN KEY (MA_NHAN_VIEN) REFERENCES NHAN_VIEN
	

